name: succucare_app
description: SuccuCare App Project
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.7.2

dependencies:
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.10
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  freezed: ^3.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - .env